### PR TITLE
NCSDIS: Reordered and added linebreaks for help

### PR DESCRIPTION
**Pull request by NAAleks**
Reorganized the follow the: information about the program, modes, games, and minor switches format. Also added a blank space after each category.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
In principle, that's what I wanted, yes. :)

However, please wrap the explanation in your git commit message to 70 characters.

**Comment by NAAleks** [comment]
Whoops, forgot about that but. I went ahead and changed it.

**Comment by DrMcCoy** [comment]
Merged, thanks! :)

Could you check through the other tools that their help messages are similarily formated?

I.e.:
- An empty line between help/version and the rest of the options (if there's no more options, don't add another empty line, though)
- Options that belong to the same "group" should be separated from other groups with an empty line

**Comment by NAAleks** [comment]
I'll keep an eye open for those.

**Pull request merged**
