### PR TITLE
IMAGES: Fix TPC TXI reading in multi mipmap images

### PR DESCRIPTION
**Pull request by Nostritius**
My second try for fixing the tpc problem #42

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Yeah, this is better (it works for C_Wraid02.tpc), but it still fails for KotOR2's 002_EBO_Inside4b.tpc, for example.

It now seems to work for TPC that don't contain TXI data, but fails for (non-animated?) TPC that do have TXI data, including all the cubemaps (CM_*).

**Comment by DrMcCoy** [comment]
(For testing, I just extracted swpc_tex_gui.erf and swpc_tex_tpa.erf in the texturepacks directory and ran

```for i in *.tpc; do echo "$i"; xoreostex2tga "$i" "$i.tga"; done```

over it. I also have a build from before ecfb314, i.e. the direct parent 9007c52, and can just see where it fails with the newer build.)

**Comment by Nostritius** [comment]
Ok, now most of the images should once more be readable. There are a few exceptions, but they were not readable even before.

**Comment by DrMcCoy** [comment]
Yes, seems to work completely again now, thanks! :)

Merged as 34649c0...9c1d845. I also added a commits that change some TXI option types to float (among them "fps"), so a few more files work now.

**Pull request closed without merging**
