### PR TITLE
IMAGES: Fix TPC TXI reading in multi mipmap images

### LINKED ISSUE #42: XOREOSTEX2TGA: Failure to convert many TPC files
(This was introduced with @Nostritius's ecfb314)

xoreostex2tga now fails to convert many KotOR TPCs, with a "Invalid UTF-8" error thrown. C_Wraid02.tpc is one example.

That example file has no attached TXI data, and I guess it tries to read other binary data as TXI, thus throwing. I.e. the offset after reading the mipmap data, before reading the TXI data, is not at the end of the file.

### PR DESCRIPTION
**Pull request by Nostritius**
This PR should fix #42 by only loading TXI data if there is more than one mipmap.

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Errm, you're using spaces for indentation here...

Also, the code does the opposite of what you state here? You're only loading TXI data if there's exactly one mipmap?

Also also, what does the mipmap count have to do with the TXI data?

I'm sorry, but I'm completely confused by this PR.

**Comment by Nostritius** [comment]
Yeah, the spaces are now fixed.
Yes I'm loading the TXI Data only if there is one mipmap because animated tpc images have 
always mipMapCount=1 And I'm loading the mipmap data only for the purpose of determining, if the image is animated. So if the mipMapCount is not equal 1 it can't be an animated image and for that i don't need to load the TXI data.

**Comment by DrMcCoy** [comment]
> Yeah, the spaces are now fixed.

Nope  :P

Untitled

> Yes I'm loading the TXI Data only if there is one mipmap because animated tpc images have always mipMapCount=1

I dunno, that sounds like a bit of a hack...

It's especially not something we can apply to xoreos proper, because we need the TXI data for other things than just determining the animation parameters.

I'd be much more happy with a proper fix instead of this workaround.

**Comment by Nostritius** [comment]
Ok, i will rethink this.

**Comment by DrMcCoy** [comment]
Thanks! :)

**Pull request closed without merging**
