### PR TITLE
Added functionality to fix broken XML. 

### PR DESCRIPTION
**Pull request by asr1**
Presently fixUnclosedNodes only works for &lt;/UIButton&gt;

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Interesting to see this in progress. :)

When integrating this into xoreos-tools / xoreos proper, the interface should probably be something like for [Aurora::Small](https://github.com/xoreos/xoreos-tools/blob/master/src/aurora/smallfile.h), i.e. a method that consumes a Common::SeekableReadStream * and spits out a fixed Common::SeekableReadStream *. It should probably live in the Aurora namespace, too.

In the method, you would create a Common::MemoryWriteStreamDynamic [1] and writeString() your fixed strings into that. Of course, our stream classes are primed to read/write Common::UString instead of std::string [2], so you either need to write a custom readline() that reads into a std::string, or change the code to use Common::UString directly. You would need to rewrite lots of your function to use iterators instead of indices, though. And possibly add some required methods to Common::UString()?

[1] Which right now allocates memory in 32 byte blocks. I should probably change that so that it doubles it capacity each time, to amortize the costs for copying
[2] Since you're only checking for certain characters and keep the rest untouched / copied verbatim, your code is probably otherwise completely utf-8-safe with std::string

**Comment by DrMcCoy** [comment]
Hej, just wanted to check in. Will you still work on this? :)

If you don't have time, don't want to work on this anymore, or anything, it's of course completely fine.

If there is anything I can help you with, hit me up, either here, per email or IRC.

**Comment by asr1** [comment]
Oh wow! Life has really gotten in the way, I'd mostly forgotten about this!
Sorry for completely dropping off the planet.

I'm interested in working on it again, absolutely. Let me take a look at
where I left off....wow, almost three years ago! And see what remains to be
done.

Alex

**Comment by DrMcCoy** [comment]
For some reason, the history of this PR/branch is really weird. 8edb21d is really huge? These two commits are a mess, to be honest.

Can you fix this? Alternatively, can you start from scratch with an up-to-date checkout from the current master branch and rebuild your changes on top?

**Comment by DrMcCoy** [comment]
There's also a lot of style things still wrong, and all source code filenames should lowercase.

Please have a look through the [Developer Central page](https://wiki.xoreos.org/index.php?title=Developer_Central) on our wiki, especially the [Code Formatting Conventions](https://wiki.xoreos.org/index.php?title=Code_Formatting_Conventions). If in doubt, look at how the existing code handles things. If still in doubt, always feel free to ask me; poke me here, on IRC or by mail. :)

**Pull request closed without merging**
